os: Ubuntu2004
platform:
  - x64
# install:
#   - sudo apt update
#   - sudo apt install ca-certificates
#   - . /etc/os-release
#   - echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
#   - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
#   - sudo apt update
#   - sudo apt -y upgrade
#   - sudo apt -y install podman
# build_script:
#   - git clone https://github.com/extra2000/greenbone-gvm-libs.git -b v21.4.4 ${APPVEYOR_BUILD_FOLDER}/src/gvm-libs
#   - git clone https://github.com/extra2000/greenbone-pg-gvm.git ${APPVEYOR_BUILD_FOLDER}/src/pg-gvm
#   - git clone https://github.com/extra2000/greenbone-gvmd.git -b v21.4.4 ${APPVEYOR_BUILD_FOLDER}/src/gvmd
#   - git clone https://github.com/extra2000/greenbone-openvas-scanner.git -b 21.4.4-rootless-podman-fix ${APPVEYOR_BUILD_FOLDER}/src/openvas-scanner
#   - git clone https://github.com/extra2000/greenbone-ospd-openvas.git -b v21.4.4 ${APPVEYOR_BUILD_FOLDER}/src/ospd-openvas
#   - git clone https://github.com/extra2000/greenbone-gsad.git -b v21.4.4 ${APPVEYOR_BUILD_FOLDER}/src/gsad
#   - git clone https://github.com/extra2000/greenbone-gsa.git -b v21.4.4 ${APPVEYOR_BUILD_FOLDER}/src/gsa
#   - cd ${APPVEYOR_BUILD_FOLDER}/src
#   - sudo podman build -t extra2000/greenbone/gse-base -f Dockerfile.gse-base .
#   - sudo podman build -t extra2000/greenbone/gvmd -f Dockerfile.gvmd .
#   - sudo podman build -t extra2000/greenbone/pg-gvm -f Dockerfile.pg-gvm .
#   - sudo podman build -t extra2000/greenbone/openvas-scanner -f Dockerfile.openvas-scanner .
#   - sudo podman build -t extra2000/greenbone/ospd-openvas -f Dockerfile.ospd-openvas .
#   - sudo podman build -t extra2000/greenbone/gsad -f Dockerfile.gsad .
#   - sudo podman build -t extra2000/greenbone/gsa -f Dockerfile.gsa .
#   - cd ${APPVEYOR_BUILD_FOLDER}
on_success:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh
  - sudo bash install.sh
  - nvm install lts/*
  - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
  - npx semantic-release
test: off
